import React,{useState,useEffect} from 'react';
import {createRoot} from 'react-dom/client';
import {Activity,ArrowUpRight,Check,ChevronDown,ChevronRight,Copy,ExternalLink,Eye,Flag,Gamepad2,LayoutDashboard,Layers,Maximize2,Monitor,MoreHorizontal,Radio,Settings2,Shield,SlidersHorizontal,Swords,Trophy,Users,Wifi,Zap} from 'lucide-react';
import {motion} from 'framer-motion';
import {feedNextAction,type GsiDiagnostics,type MatchState,type PlayerState} from '../server/state';
import type {KillEvent} from '../server/events';
import {configSides,type ResolvedSides} from '../server/sides';
import {seriesState,type SeriesState} from '../server/series';
import {phaseView} from './phases';
import {formatClock,interpolatedClock} from './clock';
import {calibrationFor,radarPoints,type RadarConfig} from './radar';
import type {RoundEvent} from '../server/events';
import {demo,demoEvents} from './demo';
import './style.css';
const OUTPUT_ROUTES=['/obs','/game'];
// Trailing slashes are tolerated; Vite/express serve the same SPA document for either form.
const isOutputRoute=OUTPUT_ROUTES.includes(location.pathname.replace(/\/+$/,'')||'/');
// Opt-in browser-only aid: /obs?checker=1 draws a checkerboard behind the canvas so an operator can
// prove the page is transparent in a normal browser. Never add it to the OBS source URL.
const showChecker=isOutputRoute&&new URLSearchParams(location.search).get('checker')==='1';
// Tag the document transparent *before* the first paint. OBS composites the browser source over the
// game capture, so any html/body background (or one applied only after mount) shows up as black bars
// covering the whole frame. Doing this at module scope guarantees frame one is already transparent.
if(isOutputRoute){document.documentElement.classList.add('output-root');document.body?.classList.add('output-body')}
type Controls={scene:string;radar:boolean;killfeed:boolean;lowerThird:boolean;economy:boolean;techPause:boolean;swapped:boolean};
const initial:Controls={scene:'live',radar:true,killfeed:true,lowerThird:true,economy:false,techPause:false,swapped:false};
function useFeed(){const [data,setData]=useState<any>(null),[connected,setConnected]=useState(false);useEffect(()=>{let ws:WebSocket;let retry:ReturnType<typeof setTimeout>;let stopped=false;function connect(){ws=new WebSocket(`${location.protocol==='https:'?'wss:':'ws:'}//${location.host}/ws`);ws.onopen=()=>setConnected(true);ws.onmessage=e=>{try{setData(JSON.parse(e.data))}catch{}};ws.onclose=()=>{setConnected(false);if(!stopped)retry=setTimeout(connect,1500)}}connect();return()=>{stopped=true;clearTimeout(retry);ws?.close()}},[]);return {data,connected}}
function Mark({other=false}:{other?:boolean}){return <span className={'team-mark '+(other?'other':'')}>{other?<><i/><i/><i/></>:<><i/><i/></>}</span>}
function Weapon(){return <svg viewBox="0 0 80 25" fill="currentColor"><path d="M4 11h13l5-5h32v3h23v3H53l-5 4H36l-2 8h-6l-1-9H14L4 19z"/><path d="M40 15h9l5 8h-8z"/></svg>}
function Strip({p,observed}:{p:PlayerState;observed:boolean}){const health=p.state?.health||0;return <div className={'player '+(!health?'dead ':'')+(observed?'observed':'')}><div className="player-line"><span className="slot">{p.observer_slot??'–'}</span><b>{p.name}</b><span className="hp">{health?health:'×'}</span></div><div className="player-meta"><span>${(p.state?.money||0).toLocaleString()}</span><Shield size={10}/><span>{p.match_stats?.kills||0} / {p.match_stats?.deaths||0}</span>{health>0&&<Weapon/>}</div><div className="health" style={{width:health+'%',background:health>50?'var(--team)':health>25?'#e6c567':'#eb6b6b'}}/></div>}
// The single panel that answers "why is nothing showing?": CS2 never sent, every packet 401'd,
// packets rejected on shape, or CS2 playing instead of spectating. Diagnostics never carry the token.
function FeedPanel({gsi,now,connected}:{gsi?:GsiDiagnostics;now:number;connected:boolean}){
 const age=gsi?.lastPacketAt?now-gsi.lastPacketAt:null;
 const ageLabel=!gsi?.lastPacketAt?'never':age!<1500?'just now':age!<60000?`${Math.round(age!/1000)}s ago`:`${Math.round(age!/60000)}m ago`;
 const state_=!connected?'offline':gsi?.accepted&&gsi.lastPacketAge<5000?'receiving':gsi?.accepted?'stale':'waiting';
 return <section className="panel feed-panel">
  <div className="panel-heading"><h2>CS2 feed <span className={'feed-state '+state_}>{connected?state_.toUpperCase():'HOST OFFLINE'}</span></h2><span className="feed-uri">{gsi?.uri||'http://127.0.0.1:8080/gsi'}</span></div>
  <div className="feed-body">
   <div className="feed-counters">{[{v:gsi?.accepted??0,l:'ACCEPTED',cls:'ok'},{v:gsi?.rejectedAuth??0,l:'TOKEN-REJECTED',cls:(gsi?.rejectedAuth?'bad':'')},{v:gsi?.rejectedShape??0,l:'SHAPE-REJECTED',cls:(gsi?.rejectedShape?'warn':'')},{v:gsi?.rejectedLate??0,l:'STALE-IGNORED',cls:(gsi?.rejectedLate?'warn':'')},{v:ageLabel,l:'LAST PACKET',cls:''}].map(({v,l,cls})=><div className={'feed-counter '+cls} key={l}><b>{v}</b><small>{l}</small></div>)}</div>
   <div className="feed-blocks">{gsi&&Object.keys(gsi.blocks).length?Object.entries(gsi.blocks).map(([name,size])=><span className={'block-chip '+(name==='allplayers'?'hot':'')} key={name}>{name} ×{size}</span>):<span className="block-chip empty">no blocks yet</span>}</div>
   <div className="feed-meta"><span>PROVIDER <b>{gsi?.provider||'—'}</b></span><span>PORT <b>{gsi?.port??'—'}</b></span><span>TOKEN SOURCE <b>{gsi?.tokenSource??'—'}</b></span><span>SUBTREE ISSUES <b>{gsi?.subtreeIssues??0}</b></span></div>
   <p className={'feed-hint '+(state_==='receiving'?'good':'')}>{feedNextAction(gsi)}</p>
  </div></section>;
}
// Radar: live GSI positions projected through the operator's calibration. The image is optional —
// without it the grid still shows where everyone is, which is what calibration debugging needs.
function Radar({state,sides,radars}:{state:MatchState;sides:ResolvedSides;radars?:RadarConfig}){
 const cal=calibrationFor(radars,state.map?.name);
 const [imageOk,setImageOk]=useState(true);
 if(!cal) return null;
 const {dots,bomb}=radarPoints(state,cal,{colors:{CT:sides.CT.color,T:sides.T.color}});
 const fresh=Date.now()-(state.provider?.timestamp??0)*1000<5000;
 return <div className={'radar'+(imageOk&&cal.image?' with-image':'')}>
  {imageOk&&cal.image?<img src={'/'+cal.image.replace(/^\//,'')} alt="" onError={()=>setImageOk(false)}/>:<div className="radar-grid"><span>RADAR IMAGE MISSING</span><small>public/{cal.image}</small></div>}
  {dots.map(dot=><i key={dot.steamid} className={'dot'+(dot.side==='CT'?' ct':' t')+(dot.alive?'':' dead')+(dot.observed?' observed':'')} style={{left:dot.u*100+'%',top:dot.v*100+'%',['--team']:dot.color||(dot.side==='CT'?'#b7a0ed':'#d8eab0')} as any} title={dot.name}>
   {dot.observed&&dot.yaw!==undefined&&<b style={{transform:`rotate(${dot.yaw}deg)`}}/>}
  </i>)}
  {bomb&&<i className={'bomb'+(bomb.planted?' planted':'')} style={{left:bomb.u*100+'%',top:bomb.v*100+'%'}}/>}
  <span className="radar-label">{state.map?.name?.replace('de_','').toUpperCase()||'—'}<small>{dots.length} TRACKED</small></span>
 </div>;
}
const radarDesc=(calibration:any,map?:string)=>calibration?`Live positions · ${map?.replace('de_','').toUpperCase()}`:`No calibration for ${map||'the current map'}`;
const seriesFormat=(series?:SeriesState,config?:any)=>(series?.format||seriesState({},config).format).toUpperCase();
const WEAPON_LABELS:Record<string,string>={weapon_ak47:'AK-47',weapon_m4a1:'M4A4',weapon_m4a1_silencer:'M4A1-S',weapon_awp:'AWP',weapon_deagle:'DEAGLE',weapon_usp_silencer:'USP-S',weapon_glock:'GLOCK',weapon_knife:'KNIFE',weapon_hegrenade:'HE',weapon_flashbang:'FLASH',weapon_smokegrenade:'SMOKE',weapon_molotov:'MOLLY',weapon_incgrenade:'INCENDIARY',weapon_decoy:'DECOY',weapon_ssg08:'SSG 08',weapon_aug:'AUG',weapon_sg556:'SG 553',weapon_famas:'FAMAS',weapon_galilar:'GALIL',weapon_mp9:'MP9',weapon_mp7:'MP7',weapon_mp5sd:'MP5-SD',weapon_ump45:'UMP-45',weapon_p90:'P90',weapon_mac10:'MAC-10',weapon_bizon:'BIZON',weapon_nova:'NOVA',weapon_xm1014:'XM1014',weapon_mag7:'MAG-7',weapon_sawedoff:'SAWED-OFF',weapon_m249:'M249',weapon_negev:'NEGEV',weapon_tec9:'TEC-9',weapon_fiveseven:'FIVE-SEVEN',weapon_cz75a:'CZ75',weapon_p250:'P250',weapon_elite:'DUALIES',weapon_revolver:'R8',weapon_taser:'ZEUS'};
const weaponLabel=(name?:string)=>WEAPON_LABELS[name||'']||(name?name.replace('weapon_','').replace(/_/g,' ').toUpperCase():'');
const demoKills=(now:number)=>({kills:demoEvents.kills.map((kill,index)=>({...kill,at:now-index*2400}))});
// Killfeed: server-derived kills, newest first, faded out by age. Ages come from the host clock in
// the snapshot, so the entries expire on the same schedule on every output surface.
function Killfeed({events,sides}:{events?:{kills?:KillEvent[]};sides:ResolvedSides}){
 const sideColor=(side?:string)=>sides[side==='CT'?'CT':'T']?.color||(side==='CT'?'#b7a0ed':'#d8eab0');
 const now=Date.now();
 const kills=(events?.kills||[]).filter(kill=>now-kill.at<9000).slice(-5).reverse();
 if(!kills.length) return null;
 return <div className="killfeed">{kills.map(kill=><div className={'kill'+(now-kill.at>7000?' leaving':'')} key={kill.id}>
  <b style={{color:sideColor(kill.killerSide)}}>{kill.killerName||'UNKNOWN'}</b>
  <span className="kill-weapon">{weaponLabel(kill.weapon)}</span>
  <b style={{color:sideColor(kill.victimSide)}}>{kill.victimName}</b>
  {kill.headshot&&<i className="kill-hs" title="Headshot">★</i>}
 </div>)}</div>;
}
function Hud({state,controls,config,sides:resolved,resolvedSeries,radars,lastSeen,now=Date.now(),signal,events,demoMode=false}:{state:MatchState;controls:Controls;config:any;sides?:ResolvedSides;resolvedSeries?:SeriesState;radars?:RadarConfig;lastSeen?:number;now?:number;signal:boolean;events?:{kills?:KillEvent[];rounds?:RoundEvent[]};demoMode?:boolean}){const players=Object.values(state.allplayers||{});const sides=resolved||configSides(config);const series=resolvedSeries||seriesState(state,config);const pips=(side:string)=><small className="pips">{series.pips[side==='CT'?'CT':'T'].map((won:boolean,index:number)=><i key={index} className={won?'on':''}/>)}</small>;const order=(controls.swapped?['T','CT']:['CT','T']) as ('CT'|'T')[];const rosterOrder=order;const team=(side:string)=>sides[side==='CT'?'CT':'T']||{name:side,color:side==='CT'?'#b7a0ed':'#d8eab0'};const color=(side:string)=>team(side).color||(side==='CT'?'#b7a0ed':'#d8eab0');const observed=players.find(p=>p.steamid===state.player?.steamid);const activeWeapon=Object.values(observed?.weapons||{}).find(w=>w.state==='active');const clock=interpolatedClock(state,demoMode?now:(lastSeen??0),now);const secs=clock.seconds;const score=(side:string)=>side==='CT'?state.map?.team_ct?.score:state.map?.team_t?.score;const view=demoMode?phaseView(demo):phaseView(state,controls);const lastRound=(events?.rounds||[]).filter(round=>round.map===state.map?.name).pop();const roundJustEnded=!!lastRound&&Date.now()-lastRound.endedAt<15000;
return <div className={'hud '+(demoMode?'demo-hud':'')}>
 <div className="hud-event">✳ <b>{config?.event?.name||'CAMPUS CUP 2025'}</b><span>GRAND FINAL · BEST OF 3</span></div>
 <div className="scoreboard"><div className="score-team" style={{['--team']:color(order[0])} as any}><Mark/><div><b>{team(order[0]).name}</b>{pips(order[0])}</div><strong>{score(order[0])??'–'}</strong></div><div className="clock">{view.clock&&<small>{series.phase==='overtime'?`OVERTIME ${series.otPeriod??1} · ${series.roundsThisHalf}/${series.otPerHalf}`:`ROUND ${series.round} / ${series.regulationRounds}`}</small>}{view.clock&&<b className={clock.source==='bomb'?'bomb-clock':''}>{clock.source==='bomb'?'◉ ':''}{formatClock(secs,clock.source==='bomb'?1:0)}</b>}<span>{clock.defusing?'DEFUSING':state.map?.name?.replace('de_','').toUpperCase()||'WAITING'}</span></div><div className="score-team lime" style={{['--team']:color(order[1])} as any}><strong>{score(order[1])??'–'}</strong><div>{pips(order[1])}<b>{team(order[1]).name}</b></div><Mark other/></div></div>
 {!signal&&!demoMode&&<div className="signal-lost">SIGNAL LOST · Waiting for CS2 GSI</div>}
 {controls.scene!=='live'?<div className="broadcast-scene"><span>{config?.event?.name}</span><h1>{controls.scene==='break'?'WE’LL BE RIGHT BACK':controls.scene==='winner'?(series.seriesWinner?`${team(series.seriesWinner).name} WINS THE SERIES`:'WINNER'):controls.scene==='veto'?'THE SERIES':controls.scene==='lineups'?'THE LINEUPS':`${team('CT').name} vs ${team('T').name}`}</h1>{controls.scene==='veto'?config?.maps.map((m:any)=><p key={m.name}>{m.name.replace('de_','')} · {m.status} {m.score?.join(' : ')}</p>):controls.scene==='lineups'?players.map(p=><p key={p.steamid}>{p.name} · {p.team}</p>):<p>{team('CT').name} / {team('T').name} · {config?.format?.toUpperCase()}</p>}</div>:<>
 {view.banner&&<div className={'phase-banner phase-'+view.banner}>{view.banner==='freezetime'?'FREEZE TIME':view.banner==='round-over'?'ROUND OVER':'TACTICAL PAUSE'}</div>}
 {view.banner==='round-over'&&lastRound&&<div className="round-result"><span>{team(lastRound.winner||'CT').name}</span><b>{lastRound.winnerDetail?(lastRound.winnerDetail==='bomb'?'BOMB':lastRound.winnerDetail==='defuse'?'DEFUSE':(lastRound.winnerDetail as string)):'—'}</b><i>{lastRound.ctScore} : {lastRound.tScore}</i></div>}
 {view.card&&<div className={'phase-card phase-card-'+view.card.kind}><h3>{view.card.kind==='warmup'?'WARMUP':view.card.kind==='intermission'?'INTERMISSION':view.card.winner?`${team(view.card.winner).name} WINS THE MAP`:'MAP OVER'}</h3><p>{config?.event?.name||''}{config?.format?` · ${config.format.toUpperCase()}`:''}</p></div>}
 {controls.radar&&view.rosters&&<Radar state={state} sides={sides} radars={radars}/>}
 {controls.killfeed&&view.killfeed&&<Killfeed events={events} sides={sides}/>}
 {view.rosters&&rosterOrder.map((side,index)=><div className={'roster roster-'+index} key={side}><div className="roster-label">{team(rosterOrder[index]).name}<span>{rosterOrder[index]}</span></div>{Array.from({length:5},(_,i)=>{const p=players.filter(p=>p.team===side).sort((a,b)=>(a.observer_slot??99)-(b.observer_slot??99))[i];return p?<Strip key={p.steamid} p={p} observed={p.steamid===state.player?.steamid}/>:<div className="player empty" key={i}>— Waiting for player</div>})}</div>)}
 {controls.lowerThird&&view.lowerThird&&players.find(p=>p.steamid===state.player?.steamid)&&<div className="lower-third"><span className="avatar"><Users size={23}/></span><div><small>OBSERVING · {observed?.team||'–'}</small><b>{players.find(p=>p.steamid===state.player?.steamid)?.name}</b></div><Weapon/><span>{activeWeapon?.ammo_clip??'–'} <small>/ {activeWeapon?.ammo_reserve??'–'}</small></span></div>}
 {controls.economy&&<div className="hud-banner">TEAM ECONOMY · ${players.filter(p=>p.team==='CT').reduce((a,p)=>a+(p.state?.money||0),0).toLocaleString()} / ${players.filter(p=>p.team==='T').reduce((a,p)=>a+(p.state?.money||0),0).toLocaleString()}</div>}
 </>}
 <div className="hud-footer"><span>SCOUT<span className="tiny-plus">+</span></span><span>{demoMode?'DEMO FEED · NOT LIVE GAME DATA':'EXTERNAL GSI FEED'}</span></div>
 </div>}
const sceneList=[{id:'live',title:'Live game',desc:'In-game spectator HUD',icon:Gamepad2},{id:'matchup',title:'Matchup',desc:'Team vs. team introduction',icon:Swords},{id:'lineups',title:'Lineups',desc:'Meet the starting five',icon:Users},{id:'veto',title:'Map series',desc:'Picks, bans & map scores',icon:Layers},{id:'winner',title:'Winner',desc:'The victory moment',icon:Trophy},{id:'break',title:'Break',desc:'A moment between the action',icon:Monitor}];
function App(){const {data,connected}=useFeed();const [tab,setTab]=useState('Overview');const [demoMode,setDemoMode]=useState(true);const [controls,setControls]=useState<Controls>(initial);const [notice,setNotice]=useState('');const [now,setNow]=useState(Date.now());const [expanded,setExpanded]=useState(false);useEffect(()=>{const id=setInterval(()=>setNow(Date.now()),100);return()=>clearInterval(id)},[]);useEffect(()=>{if(data?.controls)setControls(data.controls)},[data?.controls]);const signal=connected&&!!data?.lastSeen&&(now-data.lastSeen<5000);async function update(patch:Partial<Controls>){try{const res=await fetch('/api/controls',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({...controls,...patch})});if(!res.ok)throw Error();setControls(await res.json());setNotice('Broadcast settings saved')}catch{setNotice('Unable to save. Check the host connection.')}setTimeout(()=>setNotice(''),3500)}
const state=demoMode?demo:(signal?data?.state||{}:{});const events=demoMode?demoKills(now):data?.events;const sides=configSides(data?.config);if(isOutputRoute)return <Output state={signal?data?.state||{}:{}} controls={controls} config={data?.config} sides={demoMode?undefined:data?.sides} signal={signal} events={{kills:(data?.events?.kills||[]).filter((kill:KillEvent)=>now-kill.at<9000)}}/>;
return <div className="app"><aside className="sidebar"><a className="brand" href="/"><span className="brand-symbol">✳</span> scout<span className="brand-dot">®</span></a><div className="workspace"><span className="workspace-icon">C</span><div>Campus Cup 2025<small>Tournament workspace</small></div><ChevronDown size={15}/></div><div className="nav-label">WORKSPACE</div><nav>{[{name:'Overview',icon:LayoutDashboard},{name:'Match setup',icon:Swords},{name:'Teams & players',icon:Users},{name:'Broadcast scenes',icon:Layers},{name:'Overlay settings',icon:SlidersHorizontal}].map(({name,icon:Icon})=><button key={name} className={tab===name?'active':''} onClick={()=>setTab(name)}><Icon size={18}/>{name}{name==='Overview'&&<span className="nav-active-dot"/>}</button>)}</nav><div className="sidebar-bottom"><div className="host-card"><span className={'status-dot '+(connected?'':'off')}/><b>{connected?'Overlay host online':'Host reconnecting'}</b><small>PORT 8080 <span>v0.1.0</span></small></div><button className="settings-link" onClick={()=>setTab('Setup guide')}><Settings2 size={18}/>Setup guide<ArrowUpRight size={15}/></button><div className="operator"><span>OP</span><div>Observer station<small>Local operator</small></div><MoreHorizontal size={18}/></div></div></aside>
 <main><header><div className="breadcrumb">Workspace <ChevronRight size={13}/> <span>{tab}</span></div><div className="header-right"><span className="local-pill"><span className="status-dot"/> LOCAL SESSION</span><span className="header-separator"/><span className="help" onClick={()=>setTab('Setup guide')}>?</span></div></header><div className="content"><div className="page-title"><div><div className="eyebrow">YOUR BROADCAST, UNDER CONTROL</div><h1>{tab==='Overview'?'Broadcast overview':tab}</h1><p>Every round. Every detail. Ready for the big stage.</p></div><a className="button primary" href="/obs" target="_blank">Open broadcast <ArrowUpRight size={16}/></a></div>
 <div className="status-cards"><div className="metric"><span className="metric-icon green"><Radio size={20}/></span><div><small>GSI CONNECTION</small><b>{signal?'Receiving live data':'Waiting for CS2'}<span className={'status-dot '+(signal?'':'amber')}/></b><p>{signal?'Observer feed connected':'Demo available in preview'}</p></div><Activity className="metric-end" size={23}/></div><div className="metric"><span className="metric-icon purple-bg"><Swords size={20}/></span><div><small>CURRENT MATCH</small><b>{sides.CT.name} <span className="muted">vs</span> {sides.T.name}</b><p>Grand final <span>·</span> Best of 3</p></div></div><div className="metric"><span className="metric-icon gold"><Layers size={20}/></span><div><small>ACTIVE SCENE</small><b>{sceneList.find(s=>s.id===controls.scene)?.title}</b><p>{controls.scene==='live'?'In-game spectator HUD':'Full-screen broadcast graphic'}</p></div><span className="on-air">OUTPUT</span></div></div>
 {(tab==='Overview'||tab==='Setup guide')&&<FeedPanel gsi={data?.gsi} now={now} connected={connected}/>}
 {(tab==='Overview'||tab==='Overlay settings')&&<div className={'middle-grid '+(expanded?'expanded':'')}><section className="panel preview-panel"><div className="panel-heading"><h2>Overlay preview <span className="preview-pill">{demoMode?'DEMO':'LIVE'}</span></h2><div><button title="Toggle demo feed" className="text-button" onClick={()=>setDemoMode(!demoMode)}><span className={'status-dot '+(!demoMode?'':'amber')}/>{demoMode?'Demo feed':'GSI feed'}</button><button className="icon-button" title="Expand preview" onClick={()=>setExpanded(!expanded)}><Maximize2 size={15}/></button></div></div><div className="preview-wrap"><div className="preview-stage"><div className="map-backdrop"><div className="building one"/><div className="building two"/><div className="archway"/><div className="pavement"/></div><div className="preview-hud"><Hud state={state} controls={controls} config={data?.config} sides={demoMode?undefined:data?.sides} resolvedSeries={demoMode?undefined:data?.series} radars={data?.radars} lastSeen={data?.lastSeen} now={now} signal={signal} events={events} demoMode={demoMode}/></div><span className="preview-watermark">LAYOUT PREVIEW</span></div></div><div className="preview-bottom"><span><span className="status-dot"/> Shared overlay renderer</span><span>1920 × 1080 <i/> 16:9 <i/> Transparent output</span></div></section><section className="panel quick-controls"><div className="panel-heading"><h2>Quick controls</h2><SlidersHorizontal size={16}/></div><div className="controls-body"><div className="section-label">HUD ELEMENTS</div>{[{key:'radar',label:'Radar',desc:radarDesc(calibrationFor(data?.radars,state.map?.name),state.map?.name),disabled:!calibrationFor(data?.radars,state.map?.name)},{key:'killfeed',label:'Killfeed',desc:'Derived kills & round results'},{key:'lowerThird',label:'Player lower-third',desc:'Observed player details'},{key:'economy',label:'Economy panel',desc:'Team money comparison'}].map(item=><div className={'toggle-row '+(item.disabled?'disabled':'')} key={item.key}><div><b>{item.label}</b><small>{item.desc}</small></div><button disabled={item.disabled} aria-label={'Toggle '+item.label} aria-pressed={controls[item.key as keyof Controls] as boolean} className={'toggle '+(controls[item.key as keyof Controls]?'enabled':'')} onClick={()=>update({[item.key]:!controls[item.key as keyof Controls]})}><i/></button></div>)}<div className="control-divider"/><div className="section-label">MATCH CONTROLS</div><button className={'control-button '+(controls.techPause?'selected':'')} onClick={()=>update({techPause:!controls.techPause})}><span><span className="pause-icon">Ⅱ</span>Technical pause</span><span>{controls.techPause?'ON':'OFF'}</span></button><button className="control-button" onClick={()=>update({swapped:!controls.swapped})}><span><span className="swap-icon">⇄</span>Swap team sides</span><ChevronRight size={14}/></button><div className="controls-note"><Shield size={13}/> Changes sync to all output views</div></div></section></div>}
 {(tab==='Overview'||tab==='Broadcast scenes')&&<section className="scene-section"><div className="section-heading"><h2>Broadcast scenes <span>One click. On air.</span></h2><button className="text-button" onClick={()=>setTab(tab==='Overview'?'Broadcast scenes':'Overview')}>{tab==='Overview'?'View all scenes':'Back to overview'}<ArrowUpRight size={14}/></button></div><div className="scene-grid">{sceneList.map(({id,title,desc,icon:Icon},i)=><button className={'scene-card '+(controls.scene===id?'chosen':'')} key={id} onClick={()=>update({scene:id})}><div className={'scene-art art-'+id}><span className="scene-number">0{i+1}</span>{id==='live'?<div className="mini-hud"><i/><i/><i/><i/><b>8 <em>1:24</em> 6</b></div>:id==='matchup'?<div className="mini-match"><Mark/><span>VS</span><Mark other/></div>:id==='veto'?<div className="mini-maps"><i/><i/><i/></div>:id==='lineups'?<div className="mini-players">{[1,2,3,4,5].map(n=><Users key={n} size={22}/>)}</div>:<Icon size={35} strokeWidth={1.2}/>}<span className="scene-art-label">{id==='winner'?'VICTORY':id==='break'?'STAY TUNED':''}</span>{controls.scene===id&&<span className="scene-live"><span/> ACTIVE</span>}</div><div className="scene-caption"><div><b>{title}</b><small>{desc}</small></div>{controls.scene===id?<span className="check-circle"><Check size={11}/></span>:<ChevronRight size={14}/>}</div></button>)}</div></section>}
 {(tab==='Overview'||tab==='Match setup')&&<section className="panel series-panel"><div className="panel-heading"><h2>Current series <span className="subtle-pill">{seriesFormat(data?.series,data?.config)}</span></h2><button className="text-button" onClick={()=>setTab(tab==='Overview'?'Match setup':'Overview')}>{tab==='Overview'?'Match details':'Back to overview'}<ArrowUpRight size={14}/></button></div><div className="series-content"><div className="series-teams"><Mark/><div><b>Vertex <span>vs</span> Parallax</b><small>GRAND FINAL · CAMPUS CUP 2025</small></div><Mark other/></div><div className="map-results">{(data?.config?.maps||[]).map((m:any,i:number)=><div className={'map-result '+m.status} key={m.name}><span className="map-index">0{i+1}</span><div><b>{m.name.replace('de_','')}</b><small>{m.pick==='decider'?'Decider':m.pick==='A'?'Vertex pick':'Parallax pick'}</small></div><div className="map-score"><b>{m.status==='upcoming'?'—':m.score?.join(' : ')}</b><small>{m.status==='live'?'● CONFIGURED LIVE':m.status==='done'?'FINISHED':'UP NEXT'}</small></div></div>)}</div></div>{tab==='Match setup'&&<p className="info-note">Phase 1–3: edit config/teams.json and restart the host to update teams, format, map picks and series scores. These are operator-supplied values, not live GSI scores.</p>}</section>}
 {tab==='Teams & players'&&<section className="panel detail-panel"><h2>Team rosters</h2><p>Roster configuration is read from <code>config/teams.json</code>. Live observer slots appear when CS2 connects.</p>{(data?.config?.teams||[]).map((t:any)=><div className="team-detail" key={t.id}><Mark other={t.id==='b'}/><h2>{t.name}</h2><span>{t.players.length} configured players</span></div>)}</section>}
 {tab==='Setup guide'&&<section className="panel detail-panel"><h2>Connect your observer station</h2><ol><li>Copy <code>config/gamestate_integration_overlay.cfg</code> into CS2’s <code>game/csgo/cfg</code> folder.</li><li>Set matching GSI_TOKEN and config auth token. Restart CS2 in Fullscreen Windowed and observe a match.</li><li>In OBS, add Game Capture for cs2.exe, then a Browser Source using <code>http://127.0.0.1:8080/obs</code>.</li><li>Set the Browser Source to 1920 × 1080. Disable “Shutdown source when not visible”. Do not use chroma key or Window Capture for this overlay.</li><li>The /game route shares the renderer. Native click-through and HWND tracking are not included in this milestone.</li></ol><p className="info-note">Overlay covering the game with black bars? Point the Browser Source at <code>/obs</code> (never <code>/</code> or <code>/admin</code>), leave the source’s <b>Custom CSS</b> field empty, and keep the active scene on <b>Live game</b> — the other scenes are full-screen graphics by design. To prove the page is transparent, open <code>/obs?checker=1</code> in a normal browser: the HUD should sit on a grey checkerboard, and only the HUD panels themselves should be filled.</p><button className="button" onClick={()=>navigator.clipboard.writeText('http://127.0.0.1:8080/obs').then(()=>setNotice('OBS URL copied')).catch(()=>setNotice('Copy manually: http://127.0.0.1:8080/obs'))}><Copy size={15}/>Copy OBS source URL</button></section>}
 <footer><span><span className="footer-brand">✳ scout</span> Built for the moments that matter.</span><span>GSI only <i/> No injection <i/><span className="status-dot"/> External-process architecture</span></footer></div></main>{notice&&<motion.div initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} className="toast"><Check size={16}/>{notice}</motion.div>}</div>}
function Output(props:React.ComponentProps<typeof Hud>){const [scale,setScale]=useState(Math.min(innerWidth/1920,innerHeight/1080));useEffect(()=>{document.documentElement.classList.add('output-root');document.body.classList.add('output-body');const resize=()=>setScale(Math.min(innerWidth/1920,innerHeight/1080));addEventListener('resize',resize);return()=>removeEventListener('resize',resize)},[]);return <>{showChecker&&<div className="checker-backdrop" aria-hidden="true"/>}<div className="output-canvas" style={{transform:`translate(-50%,-50%) scale(${scale})`}}><Hud {...props}/></div></>}
createRoot(document.getElementById('root')!).render(<App/>);
