import React,{useState,useEffect} from 'react';
import {createRoot} from 'react-dom/client';
import {Activity,ArrowUpRight,Check,ChevronDown,ChevronRight,Copy,ExternalLink,Eye,Flag,Gamepad2,LayoutDashboard,Layers,Maximize2,Monitor,MoreHorizontal,Radio,Settings2,Shield,SlidersHorizontal,Swords,Trophy,Users,Wifi,Zap} from 'lucide-react';
import {motion} from 'framer-motion';
import {feedNextAction,type GsiDiagnostics,type MatchState,type PlayerState} from '../server/state';
import {demo} from './demo';
import './style.css';
const OUTPUT_ROUTES=['/obs','/game'];
// Trailing slashes are tolerated; Vite/express serve the same SPA document for either form.
const isOutputRoute=OUTPUT_ROUTES.includes(location.pathname.replace(/\/+$/,'')||'/');
// Opt-in browser-only aid: /obs?checker=1 draws a checkerboard behind the canvas so an operator can
// prove the page is transparent in a normal browser. Never add it to the OBS source URL.
const showChecker=isOutputRoute&&new URLSearchParams(location.search).get('checker')==='1';
// Tag the document transparent *before* the first paint. OBS composites the browser source over the
// game capture, so any html/body background (or one applied only after mount) shows up as black bars
// covering the whole frame. Doing this at module scope guarantees frame one is already transparent.
if(isOutputRoute){document.documentElement.classList.add('output-root');document.body?.classList.add('output-body')}
type Controls={scene:string;radar:boolean;killfeed:boolean;lowerThird:boolean;economy:boolean;techPause:boolean;swapped:boolean};
const initial:Controls={scene:'live',radar:true,killfeed:true,lowerThird:true,economy:false,techPause:false,swapped:false};
function useFeed(){const [data,setData]=useState<any>(null),[connected,setConnected]=useState(false);useEffect(()=>{let ws:WebSocket;let retry:ReturnType<typeof setTimeout>;let stopped=false;function connect(){ws=new WebSocket(`${location.protocol==='https:'?'wss:':'ws:'}//${location.host}/ws`);ws.onopen=()=>setConnected(true);ws.onmessage=e=>{try{setData(JSON.parse(e.data))}catch{}};ws.onclose=()=>{setConnected(false);if(!stopped)retry=setTimeout(connect,1500)}}connect();return()=>{stopped=true;clearTimeout(retry);ws?.close()}},[]);return {data,connected}}
function Mark({other=false}:{other?:boolean}){return <span className={'team-mark '+(other?'other':'')}>{other?<><i/><i/><i/></>:<><i/><i/></>}</span>}
function Weapon(){return <svg viewBox="0 0 80 25" fill="currentColor"><path d="M4 11h13l5-5h32v3h23v3H53l-5 4H36l-2 8h-6l-1-9H14L4 19z"/><path d="M40 15h9l5 8h-8z"/></svg>}
function Strip({p,observed}:{p:PlayerState;observed:boolean}){const health=p.state?.health||0;return <div className={'player '+(!health?'dead ':'')+(observed?'observed':'')}><div className="player-line"><span className="slot">{p.observer_slot??'–'}</span><b>{p.name}</b><span className="hp">{health?health:'×'}</span></div><div className="player-meta"><span>${(p.state?.money||0).toLocaleString()}</span><Shield size={10}/><span>{p.match_stats?.kills||0} / {p.match_stats?.deaths||0}</span>{health>0&&<Weapon/>}</div><div className="health" style={{width:health+'%',background:health>50?'var(--team)':health>25?'#e6c567':'#eb6b6b'}}/></div>}
// The single panel that answers "why is nothing showing?": CS2 never sent, every packet 401'd,
// packets rejected on shape, or CS2 playing instead of spectating. Diagnostics never carry the token.
function FeedPanel({gsi,now,connected}:{gsi?:GsiDiagnostics;now:number;connected:boolean}){
 const age=gsi?.lastPacketAt?now-gsi.lastPacketAt:null;
 const ageLabel=!gsi?.lastPacketAt?'never':age!<1500?'just now':age!<60000?`${Math.round(age!/1000)}s ago`:`${Math.round(age!/60000)}m ago`;
 const state_=!connected?'offline':gsi?.accepted&&gsi.lastPacketAge<5000?'receiving':gsi?.accepted?'stale':'waiting';
 return <section className="panel feed-panel">
  <div className="panel-heading"><h2>CS2 feed <span className={'feed-state '+state_}>{connected?state_.toUpperCase():'HOST OFFLINE'}</span></h2><span className="feed-uri">{gsi?.uri||'http://127.0.0.1:8080/gsi'}</span></div>
  <div className="feed-body">
   <div className="feed-counters">{[{v:gsi?.accepted??0,l:'ACCEPTED',cls:'ok'},{v:gsi?.rejectedAuth??0,l:'TOKEN-REJECTED',cls:(gsi?.rejectedAuth?'bad':'')},{v:gsi?.rejectedShape??0,l:'SHAPE-REJECTED',cls:(gsi?.rejectedShape?'warn':'')},{v:gsi?.rejectedLate??0,l:'STALE-IGNORED',cls:(gsi?.rejectedLate?'warn':'')},{v:ageLabel,l:'LAST PACKET',cls:''}].map(({v,l,cls})=><div className={'feed-counter '+cls} key={l}><b>{v}</b><small>{l}</small></div>)}</div>
   <div className="feed-blocks">{gsi&&Object.keys(gsi.blocks).length?Object.entries(gsi.blocks).map(([name,size])=><span className={'block-chip '+(name==='allplayers'?'hot':'')} key={name}>{name} ×{size}</span>):<span className="block-chip empty">no blocks yet</span>}</div>
   <div className="feed-meta"><span>PROVIDER <b>{gsi?.provider||'—'}</b></span><span>PORT <b>{gsi?.port??'—'}</b></span><span>TOKEN SOURCE <b>{gsi?.tokenSource??'—'}</b></span><span>SUBTREE ISSUES <b>{gsi?.subtreeIssues??0}</b></span></div>
   <p className={'feed-hint '+(state_==='receiving'?'good':'')}>{feedNextAction(gsi)}</p>
  </div></section>;
}
function Hud({state,controls,config,signal,demoMode=false}:{state:MatchState;controls:Controls;config:any;signal:boolean;demoMode?:boolean}){const players=Object.values(state.allplayers||{});const teams=config?.teams||[{name:'Vertex'},{name:'Parallax'}];const ordered=controls.swapped?[teams[1],teams[0]]:teams;const getSide=(team:any,index:number)=>{const roster=team.players||[];const found=players.find(p=>roster.some((r:any)=>r.steamid===p.steamid));return found?.team||(state.map?.team_t?.name===team.name?'T':state.map?.team_ct?.name===team.name?'CT':teams.indexOf(team)===0?'CT':'T')};const sides=ordered.map(getSide);const observed=players.find(p=>p.steamid===state.player?.steamid);const activeWeapon=Object.values(observed?.weapons||{}).find(w=>w.state==='active');const secs=Math.max(0,Math.ceil(Number(state.bomb?.countdown??state.phase_countdowns?.phase_ends_in??0)));const score=(side:string)=>side==='CT'?state.map?.team_ct?.score:state.map?.team_t?.score;
return <div className={'hud '+(demoMode?'demo-hud':'')}>
 <div className="hud-event">✳ <b>{config?.event?.name||'CAMPUS CUP 2025'}</b><span>GRAND FINAL · BEST OF 3</span></div>
 <div className="scoreboard"><div className="score-team purple"><Mark/><div><b>{ordered[0].name}</b><small>● ○ ○</small></div><strong>{score(sides[0])??'–'}</strong></div><div className="clock"><small>ROUND {(state.map?.round??0)+1} / 24</small><b>{state.bomb?.state==='planted'?'◉ ':''}{Math.floor(secs/60)}:{String(secs%60).padStart(2,'0')}</b><span>{state.map?.name?.replace('de_','').toUpperCase()||'WAITING'}</span></div><div className="score-team lime"><strong>{score(sides[1])??'–'}</strong><div><b>{ordered[1].name}</b><small>○ ○ ○</small></div><Mark other/></div></div>
 {!signal&&!demoMode&&<div className="signal-lost">SIGNAL LOST · Waiting for CS2 GSI</div>}
 {controls.scene!=='live'?<div className="broadcast-scene"><span>{config?.event?.name}</span><h1>{controls.scene==='break'?'WE’LL BE RIGHT BACK':controls.scene==='winner'?'WINNER':controls.scene==='veto'?'THE SERIES':controls.scene==='lineups'?'THE LINEUPS':`${ordered[0].name} vs ${ordered[1].name}`}</h1>{controls.scene==='veto'?config?.maps.map((m:any)=><p key={m.name}>{m.name.replace('de_','')} · {m.status} {m.score?.join(' : ')}</p>):controls.scene==='lineups'?players.map(p=><p key={p.steamid}>{p.name} · {p.team}</p>):<p>{ordered[0].name} / {ordered[1].name} · {config?.format?.toUpperCase()}</p>}</div>:<>
 {[0,1].map(index=><div className={'roster roster-'+index} key={index}><div className="roster-label">{ordered[index].name}<span>{sides[index]}</span></div>{Array.from({length:5},(_,i)=>{const p=players.filter(p=>p.team===sides[index]).sort((a,b)=>(a.observer_slot??99)-(b.observer_slot??99))[i];return p?<Strip key={p.steamid} p={p} observed={p.steamid===state.player?.steamid}/>:<div className="player empty" key={i}>— Waiting for player</div>})}</div>)}
 {controls.lowerThird&&players.find(p=>p.steamid===state.player?.steamid)&&<div className="lower-third"><span className="avatar"><Users size={23}/></span><div><small>OBSERVING · {observed?.team||'–'}</small><b>{players.find(p=>p.steamid===state.player?.steamid)?.name}</b></div><Weapon/><span>{activeWeapon?.ammo_clip??'–'} <small>/ {activeWeapon?.ammo_reserve??'–'}</small></span></div>}
 {controls.economy&&<div className="hud-banner">TEAM ECONOMY · ${players.filter(p=>p.team==='CT').reduce((a,p)=>a+(p.state?.money||0),0).toLocaleString()} / ${players.filter(p=>p.team==='T').reduce((a,p)=>a+(p.state?.money||0),0).toLocaleString()}</div>}
 {controls.techPause&&<div className="hud-banner">TECHNICAL PAUSE</div>}
 </>}
 <div className="hud-footer"><span>SCOUT<span className="tiny-plus">+</span></span><span>{demoMode?'DEMO FEED · NOT LIVE GAME DATA':'EXTERNAL GSI FEED'}</span></div>
 </div>}
const sceneList=[{id:'live',title:'Live game',desc:'In-game spectator HUD',icon:Gamepad2},{id:'matchup',title:'Matchup',desc:'Team vs. team introduction',icon:Swords},{id:'lineups',title:'Lineups',desc:'Meet the starting five',icon:Users},{id:'veto',title:'Map series',desc:'Picks, bans & map scores',icon:Layers},{id:'winner',title:'Winner',desc:'The victory moment',icon:Trophy},{id:'break',title:'Break',desc:'A moment between the action',icon:Monitor}];
function App(){const {data,connected}=useFeed();const [tab,setTab]=useState('Overview');const [demoMode,setDemoMode]=useState(true);const [controls,setControls]=useState<Controls>(initial);const [notice,setNotice]=useState('');const [now,setNow]=useState(Date.now());const [expanded,setExpanded]=useState(false);useEffect(()=>{const id=setInterval(()=>setNow(Date.now()),500);return()=>clearInterval(id)},[]);useEffect(()=>{if(data?.controls)setControls(data.controls)},[data?.controls]);const signal=connected&&!!data?.lastSeen&&(now-data.lastSeen<5000);async function update(patch:Partial<Controls>){try{const res=await fetch('/api/controls',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({...controls,...patch})});if(!res.ok)throw Error();setControls(await res.json());setNotice('Broadcast settings saved')}catch{setNotice('Unable to save. Check the host connection.')}setTimeout(()=>setNotice(''),3500)}
const state=demoMode?demo:(signal?data?.state||{}:{});if(isOutputRoute)return <Output state={signal?data?.state||{}:{}} controls={controls} config={data?.config} signal={signal}/>;
return <div className="app"><aside className="sidebar"><a className="brand" href="/"><span className="brand-symbol">✳</span> scout<span className="brand-dot">®</span></a><div className="workspace"><span className="workspace-icon">C</span><div>Campus Cup 2025<small>Tournament workspace</small></div><ChevronDown size={15}/></div><div className="nav-label">WORKSPACE</div><nav>{[{name:'Overview',icon:LayoutDashboard},{name:'Match setup',icon:Swords},{name:'Teams & players',icon:Users},{name:'Broadcast scenes',icon:Layers},{name:'Overlay settings',icon:SlidersHorizontal}].map(({name,icon:Icon})=><button key={name} className={tab===name?'active':''} onClick={()=>setTab(name)}><Icon size={18}/>{name}{name==='Overview'&&<span className="nav-active-dot"/>}</button>)}</nav><div className="sidebar-bottom"><div className="host-card"><span className={'status-dot '+(connected?'':'off')}/><b>{connected?'Overlay host online':'Host reconnecting'}</b><small>PORT 8080 <span>v0.1.0</span></small></div><button className="settings-link" onClick={()=>setTab('Setup guide')}><Settings2 size={18}/>Setup guide<ArrowUpRight size={15}/></button><div className="operator"><span>OP</span><div>Observer station<small>Local operator</small></div><MoreHorizontal size={18}/></div></div></aside>
 <main><header><div className="breadcrumb">Workspace <ChevronRight size={13}/> <span>{tab}</span></div><div className="header-right"><span className="local-pill"><span className="status-dot"/> LOCAL SESSION</span><span className="header-separator"/><span className="help" onClick={()=>setTab('Setup guide')}>?</span></div></header><div className="content"><div className="page-title"><div><div className="eyebrow">YOUR BROADCAST, UNDER CONTROL</div><h1>{tab==='Overview'?'Broadcast overview':tab}</h1><p>Every round. Every detail. Ready for the big stage.</p></div><a className="button primary" href="/obs" target="_blank">Open broadcast <ArrowUpRight size={16}/></a></div>
 <div className="status-cards"><div className="metric"><span className="metric-icon green"><Radio size={20}/></span><div><small>GSI CONNECTION</small><b>{signal?'Receiving live data':'Waiting for CS2'}<span className={'status-dot '+(signal?'':'amber')}/></b><p>{signal?'Observer feed connected':'Demo available in preview'}</p></div><Activity className="metric-end" size={23}/></div><div className="metric"><span className="metric-icon purple-bg"><Swords size={20}/></span><div><small>CURRENT MATCH</small><b>Vertex <span className="muted">vs</span> Parallax</b><p>Grand final <span>·</span> Best of 3</p></div></div><div className="metric"><span className="metric-icon gold"><Layers size={20}/></span><div><small>ACTIVE SCENE</small><b>{sceneList.find(s=>s.id===controls.scene)?.title}</b><p>{controls.scene==='live'?'In-game spectator HUD':'Full-screen broadcast graphic'}</p></div><span className="on-air">OUTPUT</span></div></div>
 {(tab==='Overview'||tab==='Setup guide')&&<FeedPanel gsi={data?.gsi} now={now} connected={connected}/>}
 {(tab==='Overview'||tab==='Overlay settings')&&<div className={'middle-grid '+(expanded?'expanded':'')}><section className="panel preview-panel"><div className="panel-heading"><h2>Overlay preview <span className="preview-pill">{demoMode?'DEMO':'LIVE'}</span></h2><div><button title="Toggle demo feed" className="text-button" onClick={()=>setDemoMode(!demoMode)}><span className={'status-dot '+(!demoMode?'':'amber')}/>{demoMode?'Demo feed':'GSI feed'}</button><button className="icon-button" title="Expand preview" onClick={()=>setExpanded(!expanded)}><Maximize2 size={15}/></button></div></div><div className="preview-wrap"><div className="preview-stage"><div className="map-backdrop"><div className="building one"/><div className="building two"/><div className="archway"/><div className="pavement"/></div><div className="preview-hud"><Hud state={state} controls={controls} config={data?.config} signal={signal} demoMode={demoMode}/></div><span className="preview-watermark">LAYOUT PREVIEW</span></div></div><div className="preview-bottom"><span><span className="status-dot"/> Shared overlay renderer</span><span>1920 × 1080 <i/> 16:9 <i/> Transparent output</span></div></section><section className="panel quick-controls"><div className="panel-heading"><h2>Quick controls</h2><SlidersHorizontal size={16}/></div><div className="controls-body"><div className="section-label">HUD ELEMENTS</div>{[{key:'radar',label:'Radar',desc:'Awaiting map calibration',disabled:true},{key:'killfeed',label:'Killfeed',desc:'Event derivation · next phase',disabled:true},{key:'lowerThird',label:'Player lower-third',desc:'Observed player details'},{key:'economy',label:'Economy panel',desc:'Team money comparison'}].map(item=><div className={'toggle-row '+(item.disabled?'disabled':'')} key={item.key}><div><b>{item.label}</b><small>{item.desc}</small></div><button disabled={item.disabled} aria-label={'Toggle '+item.label} aria-pressed={controls[item.key as keyof Controls] as boolean} className={'toggle '+(controls[item.key as keyof Controls]?'enabled':'')} onClick={()=>update({[item.key]:!controls[item.key as keyof Controls]})}><i/></button></div>)}<div className="control-divider"/><div className="section-label">MATCH CONTROLS</div><button className={'control-button '+(controls.techPause?'selected':'')} onClick={()=>update({techPause:!controls.techPause})}><span><span className="pause-icon">Ⅱ</span>Technical pause</span><span>{controls.techPause?'ON':'OFF'}</span></button><button className="control-button" onClick={()=>update({swapped:!controls.swapped})}><span><span className="swap-icon">⇄</span>Swap team sides</span><ChevronRight size={14}/></button><div className="controls-note"><Shield size={13}/> Changes sync to all output views</div></div></section></div>}
 {(tab==='Overview'||tab==='Broadcast scenes')&&<section className="scene-section"><div className="section-heading"><h2>Broadcast scenes <span>One click. On air.</span></h2><button className="text-button" onClick={()=>setTab(tab==='Overview'?'Broadcast scenes':'Overview')}>{tab==='Overview'?'View all scenes':'Back to overview'}<ArrowUpRight size={14}/></button></div><div className="scene-grid">{sceneList.map(({id,title,desc,icon:Icon},i)=><button className={'scene-card '+(controls.scene===id?'chosen':'')} key={id} onClick={()=>update({scene:id})}><div className={'scene-art art-'+id}><span className="scene-number">0{i+1}</span>{id==='live'?<div className="mini-hud"><i/><i/><i/><i/><b>8 <em>1:24</em> 6</b></div>:id==='matchup'?<div className="mini-match"><Mark/><span>VS</span><Mark other/></div>:id==='veto'?<div className="mini-maps"><i/><i/><i/></div>:id==='lineups'?<div className="mini-players">{[1,2,3,4,5].map(n=><Users key={n} size={22}/>)}</div>:<Icon size={35} strokeWidth={1.2}/>}<span className="scene-art-label">{id==='winner'?'VICTORY':id==='break'?'STAY TUNED':''}</span>{controls.scene===id&&<span className="scene-live"><span/> ACTIVE</span>}</div><div className="scene-caption"><div><b>{title}</b><small>{desc}</small></div>{controls.scene===id?<span className="check-circle"><Check size={11}/></span>:<ChevronRight size={14}/>}</div></button>)}</div></section>}
 {(tab==='Overview'||tab==='Match setup')&&<section className="panel series-panel"><div className="panel-heading"><h2>Current series <span className="subtle-pill">BO3</span></h2><button className="text-button" onClick={()=>setTab(tab==='Overview'?'Match setup':'Overview')}>{tab==='Overview'?'Match details':'Back to overview'}<ArrowUpRight size={14}/></button></div><div className="series-content"><div className="series-teams"><Mark/><div><b>Vertex <span>vs</span> Parallax</b><small>GRAND FINAL · CAMPUS CUP 2025</small></div><Mark other/></div><div className="map-results">{(data?.config?.maps||[]).map((m:any,i:number)=><div className={'map-result '+m.status} key={m.name}><span className="map-index">0{i+1}</span><div><b>{m.name.replace('de_','')}</b><small>{m.pick==='decider'?'Decider':m.pick==='A'?'Vertex pick':'Parallax pick'}</small></div><div className="map-score"><b>{m.status==='upcoming'?'—':m.score?.join(' : ')}</b><small>{m.status==='live'?'● CONFIGURED LIVE':m.status==='done'?'FINISHED':'UP NEXT'}</small></div></div>)}</div></div>{tab==='Match setup'&&<p className="info-note">Phase 1–3: edit config/teams.json and restart the host to update teams, format, map picks and series scores. These are operator-supplied values, not live GSI scores.</p>}</section>}
 {tab==='Teams & players'&&<section className="panel detail-panel"><h2>Team rosters</h2><p>Roster configuration is read from <code>config/teams.json</code>. Live observer slots appear when CS2 connects.</p>{(data?.config?.teams||[]).map((t:any)=><div className="team-detail" key={t.id}><Mark other={t.id==='b'}/><h2>{t.name}</h2><span>{t.players.length} configured players</span></div>)}</section>}
 {tab==='Setup guide'&&<section className="panel detail-panel"><h2>Connect your observer station</h2><ol><li>Copy <code>config/gamestate_integration_overlay.cfg</code> into CS2’s <code>game/csgo/cfg</code> folder.</li><li>Set matching GSI_TOKEN and config auth token. Restart CS2 in Fullscreen Windowed and observe a match.</li><li>In OBS, add Game Capture for cs2.exe, then a Browser Source using <code>http://127.0.0.1:8080/obs</code>.</li><li>Set the Browser Source to 1920 × 1080. Disable “Shutdown source when not visible”. Do not use chroma key or Window Capture for this overlay.</li><li>The /game route shares the renderer. Native click-through and HWND tracking are not included in this milestone.</li></ol><p className="info-note">Overlay covering the game with black bars? Point the Browser Source at <code>/obs</code> (never <code>/</code> or <code>/admin</code>), leave the source’s <b>Custom CSS</b> field empty, and keep the active scene on <b>Live game</b> — the other scenes are full-screen graphics by design. To prove the page is transparent, open <code>/obs?checker=1</code> in a normal browser: the HUD should sit on a grey checkerboard, and only the HUD panels themselves should be filled.</p><button className="button" onClick={()=>navigator.clipboard.writeText('http://127.0.0.1:8080/obs').then(()=>setNotice('OBS URL copied')).catch(()=>setNotice('Copy manually: http://127.0.0.1:8080/obs'))}><Copy size={15}/>Copy OBS source URL</button></section>}
 <footer><span><span className="footer-brand">✳ scout</span> Built for the moments that matter.</span><span>GSI only <i/> No injection <i/><span className="status-dot"/> External-process architecture</span></footer></div></main>{notice&&<motion.div initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} className="toast"><Check size={16}/>{notice}</motion.div>}</div>}
function Output(props:React.ComponentProps<typeof Hud>){const [scale,setScale]=useState(Math.min(innerWidth/1920,innerHeight/1080));useEffect(()=>{document.documentElement.classList.add('output-root');document.body.classList.add('output-body');const resize=()=>setScale(Math.min(innerWidth/1920,innerHeight/1080));addEventListener('resize',resize);return()=>removeEventListener('resize',resize)},[]);return <>{showChecker&&<div className="checker-backdrop" aria-hidden="true"/>}<div className="output-canvas" style={{transform:`translate(-50%,-50%) scale(${scale})`}}><Hud {...props}/></div></>}
createRoot(document.getElementById('root')!).render(<App/>);
