import React,{useEffect,useMemo,useState} from 'react';
import {Activity,AlertCircle,Archive as ArchiveIcon,ArrowDownToLine,Check,ChevronRight,Clock3,Copy,FileClock,FileUp,LockKeyhole,Pause,Play,Radio,RefreshCw,Shield,Square,StopCircle,Trash2,Users,Wifi,WifiOff} from 'lucide-react';
import {buildPreflight,type CheckState,type PreflightReport} from '../server/preflight';
import type {GsiDiagnostics,MatchState} from '../server/state';
import type {ResolvedSides} from '../server/sides';
import type {RadarsConfig} from '../server/radars';
import type {ObsStatus} from '../server/obs-config';
import type {ScoutConfig} from '../server/config';
import type {OverlayConfig} from '../server/overlay';
import type {Controls,SceneId} from '../server/controls';
import {SCENE_IDS,SCENE_TITLES} from '../server/controls';
import type {PanelRole,PanelSessionView} from '../server/auth';
import {MatchStore} from '../server/state';
import {EventTracker,type EventSnapshot, type KillEvent,type RoundEvent} from '../server/events';
import {apiFetch} from './session';

const stateIcon:Record<CheckState,React.ReactNode>={ready:<Check size={14}/>,warning:<AlertCircle size={14}/>,blocked:<WifiOff size={14}/>,skipped:<span className="preflight-skipped">—</span>};
export function PreflightPanel({hostConnected,lastSeen,now,gsi,state,sides,radars,obs,config,overlay}:{hostConnected:boolean;lastSeen:number;now:number;gsi?:GsiDiagnostics;state?:MatchState;sides?:ResolvedSides;radars?:RadarsConfig;obs?:ObsStatus;config?:ScoutConfig;overlay?:OverlayConfig}){
 const report=buildPreflight({hostConnected,lastSeen,now,gsi,state,sides,radars,obs,config,overlay});
 return <section className="panel preflight-panel">
  <div className="preflight-head"><div><div className="section-label">PRODUCTION CHECKLIST</div><h2>On-air readiness <span className={'preflight-badge '+(report.ready?'ready':'blocked')}>{report.ready?'READY WITH REVIEW':'HOLD · CHECK REQUIRED'}</span></h2><p>One final pass over signal, observer data, team assignment, graphics and output connectivity.</p></div><div className="preflight-score"><b>{report.score}</b><small>READINESS</small></div></div>
  <div className="preflight-checks">{report.checks.map(check=><article className={'preflight-check '+check.state} key={check.id}><span className="preflight-icon">{stateIcon[check.state]}</span><div><b>{check.title}{check.required&&<small>REQUIRED</small>}</b><p>{check.detail}</p></div><span className="preflight-state">{check.state==='ready'?'PASS':check.state==='blocked'?'BLOCK':check.state==='skipped'?'OPTIONAL':'REVIEW'}</span></article>)}</div>
  <div className="preflight-foot"><Shield size={13}/><span>This is a readiness aid, not a substitute for checking the actual OBS Browser Source and observer machine before going on air.</span><b>{report.blockers} BLOCKERS · {report.warnings} REVIEW</b></div>
 </section>;
}

export interface ReplayFrame {state:MatchState;events:EventSnapshot;at:number;offset:number;index:number;total:number;source:string}
interface RecordingFile {name:string;bytes:number;modifiedAt:number;kind:'gsi'}
function clone<T>(value:T):T{return JSON.parse(JSON.stringify(value))}
function parseRecording(text:string,source:string):ReplayFrame[]{
 if(text.length>32*1024*1024)throw Error('Recording exceeds the 32 MB safe-preview limit.');
 const lines=text.split(/\r?\n/).filter(line=>line.trim());
 if(lines.length>100_000)throw Error('Recording contains more than 100,000 packets; split it into shorter sessions.');
 const packets:{receivedAt:number;payload:any}[]=[];
 for(let i=0;i<lines.length;i++){
  let row:any;try{row=JSON.parse(lines[i])}catch{continue}
  if(row&&row.payload&&typeof row.payload==='object'&&row.provider&&typeof row.provider==='object')packets.push({receivedAt:Number(row.receivedAt)||Date.now()+i,payload:row});
  else if(row?.payload&&typeof row.payload==='object')packets.push({receivedAt:Number(row.receivedAt)||Date.now()+i,payload:row.payload});
 }
 if(!packets.length)throw Error('No accepted GSI packets found. Choose a SCOUT JSONL recording.');
 packets.sort((a,b)=>a.receivedAt-b.receivedAt);
 const store=new MatchStore(),tracker=new EventTracker(),frames:ReplayFrame[]=[];
 const first=packets[0].receivedAt;let sampledAt=Number.NEGATIVE_INFINITY,lastAt=first;
 for(const [index,packet] of packets.entries()){
  lastAt=packet.receivedAt;const result=store.ingest(packet.payload,packet.receivedAt);if(result===false)continue;
  tracker.observe(store.state,packet.receivedAt,result.reset);
  if(packet.receivedAt-sampledAt>=250||index===packets.length-1){
   frames.push({state:clone(store.state),events:clone(tracker.snapshot()),at:packet.receivedAt,offset:Math.max(0,packet.receivedAt-first),index:frames.length,total:0,source});sampledAt=packet.receivedAt;
  }
 }
 if(!frames.length)throw Error('The recording could not be reconstructed into valid CS2 snapshots.');
 for(const frame of frames)frame.total=frames.length;
 if(frames.length===1)frames[0].offset=Math.max(0,lastAt-first);
 return frames;
}
export function ReplayStudio({onFrame,recording,onRecordingChange,onNotice,canControl}:{onFrame:(frame:ReplayFrame|null)=>void;recording?:{enabled:boolean;file:string|null;bytes:number};onRecordingChange:(enabled:boolean)=>Promise<void>;onNotice?:(message:string)=>void;canControl:boolean}){
 const [files,setFiles]=useState<RecordingFile[]>([]),[frames,setFrames]=useState<ReplayFrame[]>([]),[fileName,setFileName]=useState(''),[error,setError]=useState(''),[playing,setPlaying]=useState(false),[position,setPosition]=useState(0),[speed,setSpeed]=useState(1),[loading,setLoading]=useState(false);
 const duration=frames.at(-1)?.offset||0;
 const currentIndex=useMemo(()=>{let result=0;for(let i=0;i<frames.length;i++){if(frames[i].offset<=position)result=i;else break}return result},[frames,position]);
 const current=frames[currentIndex]||null;
 useEffect(()=>{onFrame(current?{...current,index:currentIndex,total:frames.length}:null)},[currentIndex,frames,onFrame]);
 useEffect(()=>{if(!playing)return;let last=Date.now();const timer=setInterval(()=>{const now=Date.now(),delta=Math.min(500,now-last);last=now;setPosition(old=>{const next=old+delta*speed;if(next>=duration){setPlaying(false);return duration}return next})},100);return()=>clearInterval(timer)},[playing,speed,duration]);
 async function refresh(){try{const response=await apiFetch('/api/recordings');if(response.ok){const body=await response.json();setFiles(body.files||[])}}catch{}}
 useEffect(()=>{void refresh()},[]);
 async function loadText(text:string,name:string){setLoading(true);setError('');setPlaying(false);try{const parsed=parseRecording(text,name);setFrames(parsed);setFileName(name);setPosition(0);onFrame(parsed[0]);onNotice?.(`Loaded ${parsed.length.toLocaleString()} replay checkpoints. The live /obs output is unchanged.`)}catch(reason:any){setError(reason.message||'Could not load this recording');setFrames([]);onFrame(null)}finally{setLoading(false)}}
 async function loadFile(file:File|undefined){if(!file)return;if(file.size>32*1024*1024){setError('Recording exceeds the 32 MB safe-preview limit.');return}await loadText(await file.text(),file.name)}
 async function loadSaved(file:RecordingFile){setLoading(true);setError('');try{const response=await fetch(`/api/recordings/${encodeURIComponent(file.name)}`);if(!response.ok)throw Error((await response.json().catch(()=>({}))).error||'Could not download the recording');await loadText(await response.text(),file.name)}catch(reason:any){setError(reason.message||'Could not load recording');setLoading(false)}}
 async function toggleRecording(){try{await onRecordingChange(!recording?.enabled);await refresh()}catch(reason:any){setError(reason.message||'Could not change recording state')}}
 function clear(){setPlaying(false);setFrames([]);setFileName('');setPosition(0);setError('');onFrame(null)}
 return <section className="panel replay-studio">
  <div className="editor-head"><div className="section-label">SAFE QA · NEVER WRITES INTO LIVE GSI STATE</div><h2>Replay Studio</h2><p>Play a real capture through the shared renderer in the operator preview. Seeking, slowing down or loading a recording never posts packets to the host and never changes /obs.</p></div>
  <div className="replay-record-controls"><div className="record-indicator"><span className={recording?.enabled?'record-dot active':''}/><div><b>{recording?.enabled?'Recording accepted GSI':'Recording is off'}</b><small>{recording?.file?`${recording.file} · ${(recording.bytes/1024/1024).toFixed(1)} MB`:'Opt-in recorder · 32 MB rotating files · 12-file retention'}</small></div></div><button className={'button '+(recording?.enabled?'danger-button':'')} disabled={!canControl} title={!canControl?'Claim the broadcast control lease to record GSI':''} onClick={()=>void toggleRecording()}><Radio size={14}/>{recording?.enabled?'Stop GSI recording':'Start GSI recording'}</button><button className="icon-button" title="Refresh recordings" onClick={()=>void refresh()}><RefreshCw size={14}/></button></div>
  <div className="replay-load-grid"><label className="replay-file-drop"><FileUp size={21}/><b>Open a local GSI JSONL capture</b><small>Up to 32 MB · file stays in this browser tab</small><input type="file" accept=".jsonl,.json,.txt,application/json" onChange={event=>void loadFile(event.target.files?.[0])}/></label><div className="replay-library"><div className="section-label">HOST RECORDINGS · {files.length}</div>{files.length?files.map(file=><button key={file.name} className="recording-choice" onClick={()=>void loadSaved(file)} disabled={loading}><FileClock size={14}/><span><b>{file.name}</b><small>{new Date(file.modifiedAt).toLocaleString()} · {(file.bytes/1024/1024).toFixed(1)} MB</small></span><ChevronRight size={14}/></button>):<p className="replay-empty">No saved host captures yet. Start recording before a round, or open a JSONL file.</p>}</div></div>
  {error&&<div className="replay-error"><AlertCircle size={14}/>{error}</div>}
  {frames.length>0&&<div className="replay-player">
   <div className="replay-now"><div><span className="replay-live-dot"/><small>LOCAL REPLAY PREVIEW</small><b>{fileName}</b></div><div className="replay-match-facts"><span>{current?.state.map?.name?.replace(/^de_/,'').toUpperCase()||'—'}</span><span>ROUND {current?.state.map?.round??'—'}</span><span>{current?.state.map?.team_ct?.score??0} : {current?.state.map?.team_t?.score??0}</span></div></div>
   <div className="replay-transport"><button className="icon-button" title="Previous checkpoint" disabled={!currentIndex} onClick={()=>setPosition(frames[Math.max(0,currentIndex-1)].offset)}><ArrowDownToLine size={13}/></button><button className="replay-play" onClick={()=>setPlaying(!playing)}>{playing?<Pause size={16}/>:<Play size={16}/>}<span>{playing?'Pause':'Play'}</span></button><button className="icon-button" title="Stop and return to live preview" onClick={clear}><Square size={13}/></button><label className="replay-speed">SPEED<select value={speed} onChange={event=>setSpeed(Number(event.target.value))}>{[.25,.5,1,2,4,8].map(value=><option value={value} key={value}>{value}×</option>)}</select></label><span className="replay-time">{formatMs(position)} <i>/</i> {formatMs(duration)}</span></div>
   <input className="replay-scrubber" type="range" min={0} max={Math.max(1,duration)} step={Math.max(1,Math.min(250,duration/1000||1))} value={Math.min(position,duration)} onChange={event=>{setPlaying(false);setPosition(Number(event.target.value))}} aria-label="Replay timeline"/>
   <div className="replay-timeline-labels"><span>{new Date(frames[0].at).toLocaleTimeString()}</span><span>{frames.length.toLocaleString()} reconstructed checkpoints · {formatMs(duration)}</span><span>{new Date(frames.at(-1)!.at).toLocaleTimeString()}</span></div>
   <p className="replay-safety"><Shield size={13}/>Preview only — GSI snapshots are parsed locally and rendered into the admin preview. They are never relayed to the live host or OBS.</p>
  </div>}
  {loading&&<div className="replay-loading">Reconstructing safe preview frames…</div>}
 </section>;
}
function formatMs(milliseconds:number){const total=Math.floor(Math.max(0,milliseconds)/1000);return `${Math.floor(total/60).toString().padStart(2,'0')}:${(total%60).toString().padStart(2,'0')}`}

interface ArchiveSummary {id:string;name:string;startedAt:number;endedAt:number|null;event:string;stage:string;teams:string[];maps:string[];format:string;eventCount:number;kills:number;rounds:number}
interface ArchiveDetail extends ArchiveSummary {events:{at:number;type:'kill'|'round';data:KillEvent|RoundEvent}[]}
export function MatchArchivePanel({active,canControl,onNotice}:{active?:{id:string;name:string;startedAt:number;eventCount:number}|null;canControl:boolean;onNotice?:(message:string)=>void}){
 const [archives,setArchives]=useState<ArchiveSummary[]>([]),[detail,setDetail]=useState<ArchiveDetail|null>(null),[name,setName]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function refresh(){try{const response=await fetch('/api/archive');if(response.ok){const body=await response.json();setArchives(body.archives||[])}}catch{}}
 useEffect(()=>{void refresh()},[active?.eventCount]);
 async function action(path:string,method:'POST',body?:unknown){setBusy(true);setError('');try{const response=await apiFetch(path,{method,headers:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const data=await response.json().catch(()=>({}));if(!response.ok)throw Error(data.error||'Archive action failed');onNotice?.(path.endsWith('start')?'Match archive started':'Match archive saved');await refresh();if(path.endsWith('finish'))setDetail(data)}catch(reason:any){setError(reason.message||'Archive action failed')}finally{setBusy(false)}}
 async function open(id:string){try{const response=await fetch(`/api/archive/${encodeURIComponent(id)}`);if(!response.ok)throw Error('Could not open this match archive');setDetail(await response.json())}catch(reason:any){setError(reason.message||'Could not open archive')}}
 function download(){if(!detail)return;const url=URL.createObjectURL(new Blob([JSON.stringify(detail,null,2)],{type:'application/json'}));const link=document.createElement('a');link.href=url;link.download=`SCOUT-${detail.id}.json`;link.click();URL.revokeObjectURL(url)}
 const sortedEvents=detail?.events.slice().reverse()||[];
 return <section className="panel archive-panel">
  <div className="editor-head"><div className="section-label">DURABLE MATCH HISTORY</div><h2>Session archive</h2><p>Record the match identity and derived round/kill timeline. Archives persist across restarts; GSI payload capture is separate and opt-in.</p></div>
  <div className="archive-capture-card"><div className="archive-capture-mark"><ArchiveIcon size={20}/></div><div className="archive-capture-info"><small>SESSION STATUS</small><b>{active?`Recording · ${active.name}`:'No match session active'}</b><span>{active?`${active.eventCount} derived events · started ${new Date(active.startedAt).toLocaleTimeString()}`:'Start before live play to collect a complete, reviewable match timeline.'}</span></div>{active?<button className="button danger-button" disabled={!canControl||busy} onClick={()=>void action('/api/archive/finish','POST')}><StopCircle size={14}/>End session</button>:<div className="archive-start"><input value={name} maxLength={100} placeholder="Session name (optional)" onChange={event=>setName(event.target.value)}/><button className="button primary" disabled={!canControl||busy} onClick={()=>void action('/api/archive/start','POST',{name})}><Radio size={14}/>Start archive</button></div>}</div>
  {error&&<div className="replay-error"><AlertCircle size={14}/>{error}</div>}
  <div className="archive-workspace"><div className="archive-list"><div className="archive-list-head"><span>RECENT MATCHES</span><button className="text-button" onClick={()=>void refresh()}><RefreshCw size={12}/>Refresh</button></div>{archives.length?archives.map(item=><button className={'archive-row'+(detail?.id===item.id?' active':'')} key={item.id} onClick={()=>void open(item.id)}><span className="archive-row-date">{new Date(item.startedAt).toLocaleDateString()}<small>{new Date(item.startedAt).toLocaleTimeString()}</small></span><span className="archive-row-name"><b>{item.name}</b><small>{item.teams.join(' vs ')||item.event||'SCOUT match'}</small></span><span className="archive-row-count"><b>{item.rounds}</b><small>ROUNDS</small></span><ChevronRight size={14}/></button>):<div className="archive-empty">Finished match archives will appear here.</div>}</div>
   <div className="archive-detail">{detail?<><div className="archive-detail-head"><div><small>{detail.event||'MATCH SESSION'} · {detail.format.toUpperCase()}</small><h3>{detail.name}</h3><span>{detail.teams.join(' vs ')} · {detail.maps.join(' / ')}</span></div><button className="icon-button" title="Export archive JSON" onClick={download}><ArrowDownToLine size={15}/></button></div><div className="archive-event-list">{sortedEvents.length?sortedEvents.map((event,index)=>event.type==='round'?<div className="archive-event round" key={`${event.at}-${index}`}><span className="archive-event-time">{new Date(event.at).toLocaleTimeString()}</span><b>ROUND {(event.data as RoundEvent).round+1}</b><span>{(event.data as RoundEvent).winner||'UNKNOWN'} · {(event.data as RoundEvent).reason.toUpperCase()}</span><i>{(event.data as RoundEvent).ctScore} : {(event.data as RoundEvent).tScore}</i></div>:<div className="archive-event kill" key={`${event.at}-${index}`}><span className="archive-event-time">{new Date(event.at).toLocaleTimeString()}</span><b>{(event.data as KillEvent).killerName||'UNKNOWN'}</b><span>ELIMINATED</span><b>{(event.data as KillEvent).victimName}</b>{(event.data as KillEvent).headshot&&<i>HS</i>}</div>):<div className="archive-empty">This session has no derived kill or round events yet.</div>}</div></>:<div className="archive-detail-empty"><Clock3 size={25}/><b>Select a match</b><span>Review the event timeline, then export a machine-readable session summary.</span></div>}</div>
  </div>
 </section>;
}

export function OperatorConsole({session,onNotice}:{session:PanelSessionView|null;onNotice?:(message:string)=>void}){
 const [operators,setOperators]=useState<any[]>([]),[sessions,setSessions]=useState<any[]>([]),[audit,setAudit]=useState<any[]>([]),[label,setLabel]=useState(''),[role,setRole]=useState<PanelRole>('producer'),[oneTime,setOneTime]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function refresh(){try{const [opRes,auditRes]=await Promise.all([apiFetch('/api/operators'),apiFetch('/api/audit?limit=100')]);if(opRes.ok){const body=await opRes.json();setOperators(body.operators||[]);setSessions(body.sessions||[])}if(auditRes.ok)setAudit((await auditRes.json()).entries||[])}catch{}}
 useEffect(()=>{if(session?.role==='owner')void refresh()},[session?.role]);
 async function issue(){setBusy(true);setError('');setOneTime('');try{const response=await apiFetch('/api/operators',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({label,role})});const body=await response.json();if(!response.ok)throw Error(body.error||'Could not issue access');setOneTime(body.token);setLabel('');await refresh();onNotice?.('New operator token created. Copy it now; it cannot be viewed again.')}catch(reason:any){setError(reason.message||'Could not issue operator access')}finally{setBusy(false)}}
 async function revoke(id:string){if(!window.confirm('Revoke this operator token now? Their active sessions will be closed.'))return;try{const response=await apiFetch(`/api/operators/${encodeURIComponent(id)}`,{method:'DELETE'});const body=await response.json();if(!response.ok)throw Error(body.error||'Could not revoke operator');setOperators(body.operators||[]);await refresh()}catch(reason:any){setError(reason.message||'Could not revoke operator')}}
 async function copy(){try{await navigator.clipboard.writeText(oneTime);onNotice?.('Operator token copied.')}catch{setError('Clipboard access was blocked; select and copy the token manually.')}}
 if(session?.role!=='owner')return <section className="panel detail-panel"><div className="editor-head"><div className="section-label">ACCESS POLICY</div><h2>{session?.role==='viewer'?'Read-only broadcast access':session?.role==='designer'?'Overlay design access':'Producer access'}</h2><p>{session?.role==='producer'?'Producers operate scenes, match controls, recording and match archives; a renewable control lease keeps only one producer in charge at a time.':session?.role==='designer'?'Designers can manage themes, overlay layers, radars, artwork and reusable event packs, but cannot take live broadcast control.':'This session cannot mutate the broadcast. Ask an owner for a producer or designer access token.'}</p><div className="role-scope-card"><Shield size={16}/><span><b>Signed in as {session?.operator||'operator'}</b><small>{session?.role?.toUpperCase()} · {session?.via?.toUpperCase()||'LOCAL'} · permissions enforced by the host</small></span></div></div></section>;
 return <section className="operator-console">
  <div className="panel operator-issue-panel"><div className="editor-head"><div className="section-label">IDENTITY · LEAST PRIVILEGE</div><h2>Issue operator access</h2><p>Create a named, role-scoped token for each crew member. The secret is stored only as a salted digest and shown once; revocation closes that operator’s active sessions immediately.</p></div><div className="operator-issue-row"><label className="studio-field"><span>OPERATOR NAME</span><input value={label} maxLength={64} placeholder="e.g. Broadcast Producer" onChange={event=>setLabel(event.target.value)}/></label><label className="studio-field"><span>ROLE</span><select value={role} onChange={event=>setRole(event.target.value as PanelRole)}><option value="producer">Producer · live control + match ops</option><option value="designer">Designer · themes + overlay setup</option><option value="viewer">Viewer · read only</option></select></label><button className="button primary" disabled={busy||!label.trim()} onClick={()=>void issue()}><Users size={14}/>Issue token</button></div>{error&&<div className="replay-error"><AlertCircle size={14}/>{error}</div>}{oneTime&&<div className="one-time-token"><div><small>ONE-TIME SECRET · COPY BEFORE LEAVING THIS PAGE</small><code>{oneTime}</code></div><button className="button" onClick={()=>void copy()}><Copy size={14}/>Copy token</button><button className="icon-button danger" title="Dismiss secret" onClick={()=>setOneTime('')}><StopCircle size={14}/></button></div>}</div>
  <div className="operator-admin-grid"><section className="panel operator-list-panel"><div className="panel-heading"><h2>Operator tokens <span className="subtle-pill">{operators.length} ACTIVE</span></h2><button className="text-button" onClick={()=>void refresh()}><RefreshCw size={13}/>Refresh</button></div><div className="operator-list">{operators.length?operators.map(item=><div className="operator-list-row" key={item.id}><span className={'role-avatar '+item.role}>{item.role==='producer'?'PR':item.role==='designer'?'DS':'RO'}</span><div><b>{item.label}</b><small>{item.role.toUpperCase()} · ISSUED {new Date(item.createdAt).toLocaleString()}</small></div><button className="mini-button danger" onClick={()=>void revoke(item.id)}><Trash2 size={12}/>Revoke</button></div>):<div className="archive-empty">No role-scoped tokens yet. The host’s primary token remains the owner credential.</div>}</div></section>
   <section className="panel active-sessions-panel"><div className="panel-heading"><h2>Active operator sessions <span className="subtle-pill">{sessions.length}</span></h2></div><div className="operator-list">{sessions.length?sessions.map(item=><div className="operator-list-row" key={item.id}><span className={'role-avatar '+item.role}>{item.role.slice(0,2).toUpperCase()}</span><div><b>{item.operator}</b><small>{item.role.toUpperCase()} · {item.address} · ACTIVE {new Date(item.lastSeenAt).toLocaleTimeString()}</small></div></div>):<div className="archive-empty">No remote cookie sessions are active.</div>}</div></section></div>
  <section className="panel audit-panel"><div className="panel-heading"><h2>Operator audit trail <span className="subtle-pill">LAST {audit.length}</span></h2><button className="text-button" onClick={()=>void refresh()}><RefreshCw size={13}/>Refresh</button></div><div className="audit-table"><div className="audit-row audit-header"><span>TIME</span><span>OPERATOR</span><span>ROLE</span><span>ACTION</span><span>DETAIL</span></div>{audit.length?audit.map((item,index)=><div className="audit-row" key={`${item.at}-${index}`}><span>{new Date(item.at).toLocaleString()}</span><b>{item.actor}</b><span className={'audit-role '+item.role}>{item.role}</span><span>{item.action}</span><small>{item.detail||'—'}</small></div>):<div className="archive-empty">No operator actions have been written to the audit log.</div>}</div></section>
 </section>;
}

export function EventPackPanel({canDesign,onImported,onNotice}:{canDesign:boolean;onImported:()=>void;onNotice?:(message:string)=>void}){
 const [busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[inputKey,setInputKey]=useState(0);
 async function exportPack(){setBusy(true);setError('');setMessage('');try{const response=await apiFetch('/api/pack/export');if(!response.ok){const body=await response.json().catch(()=>({}));throw Error(body.error||'Could not export event pack')}const blob=await response.blob();const disposition=response.headers.get('content-disposition')||'';const name=/filename="?([^";]+)"?/i.exec(disposition)?.[1]||'scout-event.scoutpack.json';const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=name;link.click();URL.revokeObjectURL(url);setMessage(`Exported ${name} · ${(blob.size/1024/1024).toFixed(1)} MB`);onNotice?.('Event pack downloaded.')}catch(reason:any){setError(reason.message||'Could not export pack')}finally{setBusy(false)}}
 async function importPack(file:File|undefined){if(!file)return;if(file.size>70*1024*1024){setError('Event pack exceeds the 70 MB import limit.');return}if(!window.confirm('Import this event pack? It replaces the current teams, match, bracket, radar, layout and overlay theme, and copies its artwork into this host.')){setInputKey(key=>key+1);return}setBusy(true);setError('');setMessage('');try{const raw=JSON.parse(await file.text());const response=await apiFetch('/api/pack/import',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(raw)});const body=await response.json().catch(()=>({}));if(!response.ok)throw Error(body.error||'Could not import event pack');setMessage(`Imported ${body.config?.event?.name||'event'} · ${body.assets} artwork files`);onImported();onNotice?.('Event pack imported and published to outputs.')}catch(reason:any){setError(reason.message||'Could not import event pack')}finally{setBusy(false);setInputKey(key=>key+1)}}
 return <section className="panel event-pack-panel"><div className="editor-head"><div className="section-label">PORTABLE, VERSIONED, SECRET-FREE</div><h2>Event packages</h2><p>Move an entire tournament setup between machines: teams, rosters, map order, bracket, radar calibration, overlay design, saved themes and referenced uploaded artwork. Access tokens and OBS passwords are never exported.</p></div><div className="event-pack-actions"><div><ArchiveIcon size={22}/><b>SCOUT event package</b><small>Portable JSON manifest + validated artwork · maximum 50 MB assets</small></div><button className="button" disabled={!canDesign||busy} onClick={()=>void exportPack()}><ArrowDownToLine size={14}/>{busy?'Working…':'Export current event'}</button><label className={'button primary pack-import'+(!canDesign||busy?' disabled':'')}><FileUp size={14}/>{busy?'Importing…':'Import event package'}<input key={inputKey} type="file" accept=".json,.scoutpack.json,application/json" disabled={!canDesign||busy} onChange={event=>void importPack(event.target.files?.[0])}/></label></div>{message&&<div className="pack-feedback success"><Check size={14}/>{message}</div>}{error&&<div className="pack-feedback error"><AlertCircle size={14}/>{error}</div>}{!canDesign&&<p className="studio-hint">Designer or owner permission is required to move configurations and artwork.</p>}</section>;
}

export function TouchRemote({controls,hostConnected,lease,canControl,canTakeover=false,onAction,onClaim,onRelease,onNotice}:{controls:Controls;hostConnected:boolean;lease:any;canControl:boolean;canTakeover?:boolean;onAction:(patch:Partial<Controls>)=>void;onClaim:(force?:boolean)=>Promise<void>;onRelease:()=>Promise<void>;onNotice?:(message:string)=>void}){
 const [busy,setBusy]=useState(false);
 async function claim(){setBusy(true);try{await onClaim(!!lease?.holder&&canTakeover)}finally{setBusy(false)}}
 async function release(){setBusy(true);try{await onRelease()}finally{setBusy(false)}}
 return <div className="touch-remote"><header className="touch-header"><a className="brand" href="/"><span className="brand-symbol">✳</span> scout<span className="brand-dot">®</span></a><span className={'touch-host '+(hostConnected?'':'offline')}><i/>{hostConnected?'HOST ONLINE':'HOST OFFLINE'}</span><a href="/" className="touch-exit">FULL PANEL</a></header><main className="touch-main"><div className="touch-eyebrow">REMOTE PRODUCER CONSOLE</div><h1>Show control</h1><p>Touch-first, low-latency controls for a phone or tablet on the trusted venue network.</p>
  <section className={'touch-lease'+(lease?.principalId?' held':'')}><LockKeyhole size={18}/><div><small>CONTROL LEASE</small><b>{lease?.holder?lease.mine?'Held by you':`Held by ${lease.holder}`:'Available'}</b><span>{lease?.expiresAt?`Renews until ${new Date(lease.expiresAt).toLocaleTimeString()}`:'Only one producer can send live changes at a time.'}</span></div>{lease?.mine?<button onClick={()=>void release()} disabled={busy}>Release</button>:<button onClick={()=>void claim()} disabled={!canControl||busy||!!lease?.holder&&!canTakeover}>{lease?.holder?canTakeover?'Take over':'In use':'Take control'}</button>}</section>
  <section className="touch-card"><div className="touch-section-title"><span>ON-AIR SCENE</span><small>{controls.scene.toUpperCase()}</small></div><div className="touch-scene-grid">{SCENE_IDS.map(id=><button key={id} className={controls.scene===id?'active':''} disabled={!canControl||(!lease?.mine&&!!lease?.holder)} onClick={()=>onAction({scene:id})}>{SCENE_TITLES[id]}</button>)}</div></section>
  <section className="touch-card"><div className="touch-section-title"><span>LIVE GRAPHICS</span><small>CHANGES SYNC TO ALL OUTPUTS</small></div><div className="touch-toggles">{([['killfeed','Killfeed'],['radar','Radar'],['lowerThird','Player lower third'],['economy','Economy bar'],['techPause','Technical pause'],['swapped','Swap sides']] as [keyof Controls,string][]).map(([id,title])=><button className={'touch-toggle'+(controls[id]?' on':'')} key={id} disabled={!canControl||(!lease?.mine&&!!lease?.holder)} onClick={()=>onAction({[id]:!controls[id]} as Partial<Controls>)}><span>{title}</span><b>{controls[id]?'ON':'OFF'}</b></button>)}</div></section>
  <section className="touch-card touch-break"><div className="touch-section-title"><span>BREAK COUNTDOWN</span><small>{controls.breakEndsAt?new Date(controls.breakEndsAt).toLocaleTimeString():'NOT RUNNING'}</small></div><div className="touch-break-actions">{[3,5,10,15].map(minute=><button key={minute} disabled={!canControl||(!lease?.mine&&!!lease?.holder)} onClick={()=>onAction({scene:'break',breakEndsAt:Date.now()+minute*60_000})}>{minute} MIN</button>)}<button disabled={!canControl||(!lease?.mine&&!!lease?.holder)} onClick={()=>onAction({breakEndsAt:null})}>CLEAR</button></div></section>
  {!canControl&&<div className="touch-readonly"><Shield size={15}/>This account is read-only. Ask the host owner for producer access.</div>}
 </main><footer className="touch-footer"><span><Wifi size={13}/>Same-host control API · token scoped · no cloud dependency</span><span>SCOUT · OPERATOR MODE</span></footer></div>;
}
